//! The **capability bridge** use case (F6.5, FR-18, docs/06 §6, invariant 1).
//!
//! A generated app runs in an opaque origin (F6.4, ADR-030) and can do exactly
//! one thing beyond drawing: `postMessage` the shell a **name** — one of the
//! capabilities its own manifest declares — together with a short-lived,
//! single-use capability token. This module is what happens next, and its whole
//! design is one sentence:
//!
//! > **Naming is not authorizing.** A capability token buys the right to be
//! > *evaluated*; it never buys execution.
//!
//! So the path here is deliberately the same path a model-proposed tool call
//! takes, with two extra gates in front of it and nothing removed from it:
//!
//! 1. the token must authorize this exact question (app, version, capability,
//!    device, deadline — [`jarvis_domain::appbridge::CapabilityToken`]), and it
//!    is **consumed** by asking, so a replay finds nothing;
//! 2. the capability must be **declared in the artifact's own manifest** —
//!    docs/06 §6's "undeclared capability ⇒ reject", decidable only because the
//!    vocabulary is closed (ADR-029);
//! 3. then `policy::evaluate` against the **live registry** — not the tier the
//!    capability advertises, which is a display preview and nothing more;
//! 4. then approval for anything the policy says needs it, and a real
//!    `ExecutionGrant` minted, validated and consumed for R2+;
//! 5. then execution, and an audit row either way.
//!
//! Every refusal is audited. A rejection nobody can observe is indistinguishable
//! from an absent check — and golden 8 asserts on the audit trail, not on a
//! returned error.

use jarvis_domain::appbridge::{
    BridgeDenial, CAPABILITY_TOKEN_TTL, CapabilityToken, CapabilityTokenId,
};
use jarvis_domain::artifact::{ArtifactVersion, Capability};
use jarvis_domain::audit::AuditEvent;
use jarvis_domain::grants::GrantError;
use jarvis_domain::ids::{ArtifactId, DeviceId, RunId, UserId};
use jarvis_domain::policy::ResourcePattern;
use jarvis_domain::tools::{ToolError, ToolInvocation, ToolProposal, ToolResult};

use crate::orchestrator::{Clock, Ran, run_or_cancel};
use crate::policy::{
    ApprovalGate, ApprovalOutcome, ApprovalRequest, AuditSink, GrantBinding, GrantMintError,
    GrantMinter, GrantValidator, PolicyContext, PolicyDecision, ToolRegistry, evaluate,
};
use crate::ports::{ArgumentDigest, ArtifactStore, RepositoryError};
use async_trait::async_trait;
use tokio_util::sync::CancellationToken;

/// Storage for minted capability tokens (F6.5).
///
/// **Single-use by construction:** [`Self::consume`] both looks a token up and
/// destroys it, so replay is not a rule the caller has to remember to apply — it
/// is the only operation available. Implementations are in-memory on purpose:
/// a token outliving a daemon restart would be a token outliving the app
/// instance it was minted for.
#[async_trait]
pub trait CapabilityTokenStore: Send + Sync {
    /// Store a freshly minted token. The id is generated by infra (randomness
    /// lives where `getrandom` is allowed).
    async fn put(&self, token: CapabilityToken);

    /// Take the token with this id, if one exists. **Removes it**: a second
    /// `consume` of the same id returns `None`, whatever else was true of it.
    async fn consume(&self, id: &CapabilityTokenId) -> Option<CapabilityToken>;

    /// Mint an id. Separated from [`Self::put`] so the randomness stays in infra
    /// while the binding is assembled here.
    async fn new_id(&self) -> CapabilityTokenId;
}

/// What a bridge request could not do. Split from [`BridgeDenial`] (the bridge's
/// own refusals) because everything below the policy engine is *not* the
/// bridge's decision — it is the ordinary tool path answering, and it must read
/// that way in the audit trail too.
#[derive(Debug, thiserror::Error)]
pub enum BridgeError {
    /// The bridge refused before `policy::evaluate` was reached.
    #[error(transparent)]
    Denied(#[from] BridgeDenial),
    /// `policy::evaluate` rejected the proposal.
    #[error("policy denied the operation: {0}")]
    Policy(String),
    /// A human declined, or the approval seam timed out.
    #[error("the operation was not approved")]
    NotApproved,
    #[error("grant could not be minted: {0}")]
    Grant(#[from] GrantMintError),
    #[error("grant was rejected at the executor boundary: {0}")]
    GrantRejected(#[from] GrantError),
    #[error("tool execution failed: {0}")]
    Tool(#[from] ToolError),
    #[error("the operation was cancelled")]
    Cancelled,
    #[error("storage unavailable")]
    Storage,
}

impl BridgeError {
    /// Stable machine code (docs/05 §7).
    pub fn code(&self) -> &'static str {
        match self {
            Self::Denied(d) => d.code(),
            Self::Policy(_) => "policy.denied",
            Self::NotApproved => "approval.denied",
            Self::Grant(_) => "grant.mint_failed",
            Self::GrantRejected(_) => "grant.rejected",
            Self::Tool(_) => "tool.failed",
            Self::Cancelled => "run.cancelled",
            Self::Storage => "provider.unavailable",
        }
    }
}

/// One question from a generated app. Every field except `token` is untrusted
/// content from an opaque-origin frame; `token` is untrusted too, it just
/// happens to be checkable.
#[derive(Debug, Clone)]
pub struct BridgeRequest {
    pub artifact_id: ArtifactId,
    pub version: ArtifactVersion,
    pub capability: Capability,
    /// What the app wants the operation applied to — an entity id, a list id.
    /// **Opaque and non-authorizing**: the backing tool re-resolves it through
    /// its own allowlist, so naming a target the app was never given access to
    /// fails inside the tool exactly as it would for any other caller
    /// (ADR-029).
    pub target: String,
    /// The value the operation takes, where it takes one (`state` for a light,
    /// the verified label for a scene). `None` for a pure read — and a `Some`
    /// on a read, or a `None` on a write, is a rejection rather than a default:
    /// the host builds the argument tree, so it never guesses at it.
    pub value: Option<String>,
    pub token: CapabilityTokenId,
}

/// The identity the bridge acts as. An app-originated call is still *the user's*
/// call — it is made from their device, in their session, against their home —
/// so the grant binds to them, and the audit says so.
#[derive(Debug, Clone)]
pub struct BridgeActor {
    pub user_id: UserId,
    pub device_id: DeviceId,
    /// A host-minted correlation id for this one app-originated operation.
    /// There is no conversational `Run` behind a bridge call, but a grant binds
    /// to a run id and the audit trail correlates by one, so the host mints it
    /// (randomness lives at the edge) and it appears in both.
    pub run_id: RunId,
}

/// The capability bridge.
pub struct AppBridge<'a> {
    pub artifacts: &'a dyn ArtifactStore,
    pub tokens: &'a dyn CapabilityTokenStore,
    pub registry: &'a ToolRegistry,
    pub audit: &'a dyn AuditSink,
    pub clock: &'a dyn Clock,
    pub approval_gate: &'a dyn ApprovalGate,
    pub grant_minter: &'a dyn GrantMinter,
    pub grant_validator: &'a dyn GrantValidator,
    pub arg_digest: &'a dyn ArgumentDigest,
    /// Scopes the *user's session* holds. The bridge does not widen them: an app
    /// can never reach a tool whose scope its owner's session lacks.
    pub granted_scopes: PolicyContext,
}

impl AppBridge<'_> {
    /// Mint a capability token for an app to spend on one question.
    ///
    /// Minting checks the same declaration rule the exchange does, so an
    /// undeclared capability cannot even obtain a token — the app is refused at
    /// the first step rather than being handed something that will fail later.
    pub async fn mint_token(
        &self,
        artifact_id: &ArtifactId,
        version: ArtifactVersion,
        capability: Capability,
        actor: &BridgeActor,
    ) -> Result<CapabilityToken, BridgeError> {
        self.declared(artifact_id, version, capability, actor)
            .await?;
        let token = CapabilityToken {
            id: self.tokens.new_id().await,
            artifact_id: artifact_id.clone(),
            version,
            capability,
            device_id: actor.device_id.clone(),
            expires_at: self.clock.now() + CAPABILITY_TOKEN_TTL,
        };
        self.tokens.put(token.clone()).await;
        Ok(token)
    }

    /// Exchange a capability token for one operation (docs/06 §6).
    #[allow(clippy::too_many_lines)] // One gate per paragraph; splitting it would hide the order.
    pub async fn exchange(
        &self,
        request: BridgeRequest,
        actor: &BridgeActor,
        cancel: CancellationToken,
    ) -> Result<ToolResult, BridgeError> {
        let now = self.clock.now();

        // Gate 1 — the token. Consuming *is* the lookup, so a replayed token is
        // `Unusable` on its second use without a separate replay check to
        // forget. A token that fails any binding is spent all the same: an
        // attacker gets one probe per token, never a reusable oracle.
        let Some(token) = self.tokens.consume(&request.token).await else {
            self.deny(
                &request,
                actor,
                &BridgeDenial::Token(jarvis_domain::appbridge::CapabilityTokenError::Unusable),
            )
            .await;
            return Err(BridgeDenial::Token(
                jarvis_domain::appbridge::CapabilityTokenError::Unusable,
            )
            .into());
        };
        if let Err(e) = token.authorizes(
            &request.artifact_id,
            request.version,
            request.capability,
            &actor.device_id,
            now,
        ) {
            self.deny(&request, actor, &BridgeDenial::Token(e)).await;
            return Err(BridgeDenial::Token(e).into());
        }

        // Gate 2 — the manifest. docs/06 §6's "undeclared capability ⇒ reject",
        // and golden 8's assertion. Re-checked here and not merely at mint time
        // because the manifest is the authority and mint time is not execution
        // time.
        self.declared(
            &request.artifact_id,
            request.version,
            request.capability,
            actor,
        )
        .await?;

        // The target is validated by the domain before it is put in an argument
        // tree — but validity is not authority. `home.read_state` will still
        // resolve it through its own entity allowlist, so an app naming an
        // entity it was never given fails inside the tool.
        // The **same** validation an app spec's binding target goes through
        // (F6.1) — a looser check here would be a hole in that one. Validity is
        // still not authority: `home.get_state` re-resolves the entity through
        // its own allowlist, so a well-formed target the owner never authorized
        // fails inside the tool.
        let target = jarvis_domain::appspec::BindingTarget::parse(&request.target)
            .map_err(|_| BridgeError::from(BridgeDenial::InvalidTarget))?;
        let resource: ResourcePattern = target
            .as_str()
            .parse()
            .map_err(|_| BridgeError::from(BridgeDenial::InvalidTarget))?;
        let arguments = request
            .capability
            .arguments_for(target.as_str(), request.value.as_deref())
            .map_err(|_| BridgeError::from(BridgeDenial::InvalidTarget))?;

        let proposal = ToolProposal {
            tool_id: request.capability.tool_id(),
            arguments,
        };

        // Gate 3 — the ordinary policy engine, against the LIVE registry. Note
        // what is *not* consulted: `Capability::risk()`. That is a display
        // preview (ADR-029 §4); substituting it here would be exactly the "text
        // grants authority" mistake invariant 1 forbids.
        let decision = evaluate(&proposal, self.registry, &self.granted_scopes);
        self.record(
            actor,
            match &decision {
                PolicyDecision::Auto => "policy.auto_authorized",
                PolicyDecision::NeedsApproval { .. } => "policy.approval_requested",
                PolicyDecision::Reject { .. } => "policy.denied",
            },
            &request,
            &serde_json_code(&decision),
        )
        .await;

        let run_id = actor.run_id.clone();
        let mut grant = None;
        match decision {
            PolicyDecision::Reject { reason } => {
                return Err(BridgeError::Policy(reason.code().to_owned()));
            }
            PolicyDecision::NeedsApproval { exact_effect } => {
                let policy = self
                    .registry
                    .policy_of(&proposal.tool_id)
                    .ok_or_else(|| BridgeError::Policy("policy.unknown_tool".to_owned()))?
                    .clone();
                let outcome = self
                    .approval_gate
                    .request(
                        ApprovalRequest {
                            run_id: run_id.clone(),
                            tool_id: proposal.tool_id.clone(),
                            exact_effect,
                            proposed_arguments: proposal.arguments.clone(),
                            risk: policy.risk,
                            reversible: policy.is_reversible,
                            egress: policy.egress,
                        },
                        cancel.clone(),
                    )
                    .await;
                let approved = match outcome {
                    ApprovalOutcome::Approved { arguments } => arguments,
                    ApprovalOutcome::Denied => {
                        self.record(actor, "approval.denied", &request, "{}").await;
                        return Err(BridgeError::NotApproved);
                    }
                };
                let (tool_version, _executor) = self
                    .registry
                    .resolve(&proposal.tool_id)
                    .ok_or_else(|| BridgeError::Policy("policy.unknown_tool".to_owned()))?;
                let minted = self
                    .grant_minter
                    .mint(GrantBinding {
                        user_id: actor.user_id.clone(),
                        device_id: actor.device_id.clone(),
                        run_id: run_id.clone(),
                        tool_id: proposal.tool_id.clone(),
                        tool_version,
                        arguments: approved.clone(),
                        target_resource: resource.clone(),
                        ttl: policy.timeout + CAPABILITY_TOKEN_TTL,
                    })
                    .await?;
                self.record(actor, "grant.minted", &request, "{}").await;
                grant = Some((minted, approved));
            }
            PolicyDecision::Auto => {}
        }

        let (tool_version, executor) = self
            .registry
            .resolve(&proposal.tool_id)
            .ok_or_else(|| BridgeError::Policy("policy.unknown_tool".to_owned()))?;
        let arguments = grant
            .as_ref()
            .map(|(_, approved)| approved.clone())
            .unwrap_or(proposal.arguments);
        let invocation = ToolInvocation {
            tool_id: proposal.tool_id.clone(),
            tool_version,
            arguments,
        };
        // D-M5-4: the hash of exactly what is about to execute, so the audit row
        // below answers "which arguments ran", not merely "which tool".
        let args_sha = self.arg_digest.digest(&invocation.arguments);

        let grant = match grant {
            Some((g, _)) => {
                // Validated and consumed at the executor boundary, never at
                // decision time (docs/06 §4).
                if let Err(e) = self
                    .grant_validator
                    .validate(&g, &invocation, self.clock.now())
                    .await
                {
                    self.record(actor, "grant.rejected", &request, "{}").await;
                    return Err(e.into());
                }
                Some(g)
            }
            None => None,
        };

        // Cancellation races execution, and dropping the future cancels it —
        // the orchestrator's own helper, so an app-originated call is as
        // promptly abandonable as a model-originated one (invariant 4).
        let result =
            match run_or_cancel(executor.execute(invocation, grant, cancel.clone()), &cancel).await
            {
                Ran::Cancelled => return Err(BridgeError::Cancelled),
                Ran::Done(r) => r,
            };

        let payload = format!("{{\"args_sha256\":\"{args_sha}\"}}");
        match result {
            Ok(result) => {
                self.record(actor, "tool.executed", &request, &payload)
                    .await;
                Ok(result)
            }
            Err(e) => {
                self.record(actor, "tool.failed", &request, &payload).await;
                Err(BridgeError::Tool(e))
            }
        }
    }

    /// The manifest is the authority on what an app may ask for.
    async fn declared(
        &self,
        artifact_id: &ArtifactId,
        version: ArtifactVersion,
        capability: Capability,
        actor: &BridgeActor,
    ) -> Result<(), BridgeError> {
        let manifest = match self.artifacts.get(artifact_id, version).await {
            Ok(Some(m)) => m,
            Ok(None) => {
                self.record_denial(actor, artifact_id, capability, &BridgeDenial::UnknownApp)
                    .await;
                return Err(BridgeDenial::UnknownApp.into());
            }
            Err(RepositoryError::Storage(_)) => return Err(BridgeError::Storage),
            Err(_) => return Err(BridgeError::Storage),
        };
        if !manifest.kind().renders_in_app_sandbox() {
            let denial = BridgeDenial::NotAnApp(artifact_id.clone());
            self.record_denial(actor, artifact_id, capability, &denial)
                .await;
            return Err(denial.into());
        }
        if !manifest.capabilities().contains(&capability) {
            let denial = BridgeDenial::UndeclaredCapability(capability);
            self.record_denial(actor, artifact_id, capability, &denial)
                .await;
            return Err(denial.into());
        }
        Ok(())
    }

    async fn deny(&self, request: &BridgeRequest, actor: &BridgeActor, denial: &BridgeDenial) {
        self.record_denial(actor, &request.artifact_id, request.capability, denial)
            .await;
    }

    /// Every bridge refusal is an audit row. This is the observable half of
    /// "undeclared capability ⇒ reject" — golden 8 asserts here, not on the
    /// error a caller happens to receive.
    async fn record_denial(
        &self,
        actor: &BridgeActor,
        artifact_id: &ArtifactId,
        capability: Capability,
        denial: &BridgeDenial,
    ) {
        self.audit
            .record(AuditEvent {
                occurred_at: self.clock.now(),
                actor: format!("app:{artifact_id}"),
                event_type: "app.capability_denied".to_owned(),
                target: format!("capability:{capability}"),
                correlation_id: Some(actor.device_id.to_string()),
                payload_json: format!("{{\"reason\":\"{}\"}}", denial.code()),
            })
            .await;
    }

    async fn record(
        &self,
        actor: &BridgeActor,
        event_type: &str,
        request: &BridgeRequest,
        payload_json: &str,
    ) {
        self.audit
            .record(AuditEvent {
                occurred_at: self.clock.now(),
                actor: format!("app:{}", request.artifact_id),
                event_type: event_type.to_owned(),
                target: format!("tool:{}", request.capability.tool_id()),
                correlation_id: Some(actor.device_id.to_string()),
                payload_json: payload_json.to_owned(),
            })
            .await;
    }
}

/// The decision as a short, controlled code — never a rendering of arguments
/// (invariant 5).
fn serde_json_code(decision: &PolicyDecision) -> String {
    let code = match decision {
        PolicyDecision::Auto => "auto",
        PolicyDecision::NeedsApproval { .. } => "needs_approval",
        PolicyDecision::Reject { reason } => reason.code(),
    };
    format!("{{\"decision\":\"{code}\"}}")
}
