// @ts-check
const eslint = require("@eslint/js");
const { defineConfig } = require("eslint/config");
const tseslint = require("typescript-eslint");
const angular = require("angular-eslint");

module.exports = defineConfig([
  {
    // Generated by `cargo xtask codegen` — one source of truth in
    // jarvis-contracts; style rules do not apply to machine output.
    ignores: ["src/generated/**"],
  },
  {
    files: ["**/*.ts"],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "app",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "app",
          style: "kebab-case",
        },
      ],
    },
  },
  {
    files: ["**/*.html"],
    extends: [
      angular.configs.templateRecommended,
      angular.configs.templateAccessibility,
    ],
    rules: {},
  },
  {
    // docs/12 §2.3/§9, invariant 1: no model-authored HTML on the HUD face.
    // Card content renders through Angular interpolation only — enforced here
    // (checked by `npm run lint`, part of the DoD) so the property stays
    // greppable rather than resting on review discipline alone.
    files: ["src/app/hud/**/*.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "MemberExpression[property.name='innerHTML']",
          message:
            "No innerHTML on the HUD face (docs/12 §9, invariant 1) — card content renders via Angular interpolation only.",
        },
        {
          selector:
            "MemberExpression[property.name=/^bypassSecurityTrust/]",
          message:
            "No DomSanitizer.bypassSecurityTrust* on the HUD face (docs/12 §9, invariant 1) — card content renders via Angular interpolation only.",
        },
      ],
    },
  },
]);
